name: "CLI - NodeJS Tests"

on:
  pull_request:
    branches: ['*']

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./modules/guard-cli

    steps:
    - uses: actions/checkout@v4
      with:
        path: 'modules/guard-cli'

    - uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Install, build, and test
      run: |
        cd ./modules/guard-cli
        npm ci
        npm run build
      env:
        CI: true
