name: "Explorer - Deploy"

on:
  pull_request:
    branches: ['*']
  push:
    branches:
      - "master"

jobs:
  heroku:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./modules/guard-explorer
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          appdir: 'modules/guard-explorer'
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_ADMIN}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          buildpack: "https://github.com/heroku/heroku-buildpack-nodejs"
          procfile: "web: npm run start:prod"
        env:
          HD_PORT: 80
